"""
The purpose this code is to count A, G, C, T in a string of nucleotides.

SKH + GWC 20180108
"""

def main():
    nts = "ATGCCAAACTCTTCTCGGACGCATTGCGCGCAACCACCTGCCTCACTTTCCATACCCACGCCCACGAAAAATTTAGGAGGGGGGTGGTGCCAGGTTGCTACACCGGGCTACACTAAGACAGGAAGATGAGGGGAACGCCCGGGTACAGAATCTCAACCTTTATGAGTCTTTTAGTACCTGGGATACCCTCATAATATGCGAAGGATAAGTCTCATTTCATACGAGATATGTTCCCTTGATTCGCGCAAGTGAACGCTAAACTTGACTTAGGTCGCTGCGCTAGAAAGTGACTCCGATAATAGTTGCATATGAGCGGAAGTGGATGCAGTAGATAGGGTATATTCTGTCTTACTTTAAAGATGCGTTACATACGCTAGTCCGCCAAGACAGTGCCCAAGCCCCCGAGCATTGTATCCTAGCCTACGCTACGCTGCGGCACGGTTGACACCTTATCGCCACGGATATGATCCTACAACCGGTAAACTGCTTGTTAACCCTAGATTGGTCAGCATATGATTTAGAAGGCAGTTGTAATATTCCTAAGAAACCTGCCACCGTCGACCCTTTCTCATCTTTCATGTCCACCAGGGCTTGTACTTTCTATCTTCATATATATCTCCCCTCCCTCCAGGGTCTTCCGGTGTATTTACGGGCCTTCCCTTGTTTTGCATTACTCGACCAAACAGGGAGCGAGGTACAACGTAAGTCAACACTCCAAATTGCGCCTAGACGAGGGAGGTCCGCGTAGTAAGTCCAAGCTACCCATCGATCGAGACAGGGAGTCGACGACGCCGATTCCCGAATGGCATCTTCCAACACTC"

    print("The string {0} is {1} long".format(nts, len(nts)))

    A = 0
    C = 0
    G = 0
    T = 0

    for nt in nts:
        if nt == "A":
            A += 1
        elif nt == "C":
            C += 1
        elif nt == "G":
            G += 1
        elif nt == "T":
            T += 1
        else:
            raise ValueError("Oh NO! We didn't expect {0}".format(nt))
    assert (A + C + G + T) == len(nts)
    print("{0} {1} {2} {3}".format(A, C, G, T))


    print("We are printing a string {2} {0} {1} {0}".format("HI", "BYE"))


if __name__ == '__main__':
    main()
